export const PERSOS = [
  { perso: 'Link', univers: 'The Legend of Zelda' },
  { perso: 'Mario', univers: 'Super Mario' },
  { perso: 'Samus Aran', univers: 'Metroid' },
  { perso: 'Sonic', univers: 'Sonic the Hedgehog' },
  { perso: 'Master Chief', univers: 'Halo' },
  { perso: 'Joel Miller', univers: 'The Last of Us' },
  { perso: 'Geralt de Riv', univers: 'The Witcher' },
  { perso: 'Aloy', univers: 'Horizon Zero Dawn' },
  { perso: 'Kratos', univers: 'God of War' },
  { perso: 'Lara Croft', univers: 'Tomb Raider' },
  { perso: 'Cloud Strife', univers: 'Final Fantasy VII' },
  { perso: 'Arthur Morgan', univers: 'Red Dead Redemption 2' },
  { perso: 'Ryu', univers: 'Street Fighter' },

  { perso: 'Son Goku', univers: 'Dragon Ball' },
  { perso: 'Monkey D. Luffy', univers: 'One Piece' },
  { perso: 'Mikasa Ackerman', univers: 'L’Attaque des Titans' },
  { perso: 'Naruto Uzumaki', univers: 'Naruto' },
  { perso: 'Ichigo Kurosaki', univers: 'Bleach' },
  { perso: 'Tanjiro Kamado', univers: 'Demon Slayer' },
  { perso: 'Saitama', univers: 'One Punch Man' },
  { perso: 'Edward Elric', univers: 'Fullmetal Alchemist' },
  { perso: 'Yuji Itadori', univers: 'Jujutsu Kaisen' },
  { perso: 'Kenshin Himura', univers: 'Rurouni Kenshin' },
  { perso: 'Light Yagami', univers: 'Death Note' },
  { perso: 'Eren Yeager', univers: 'L’Attaque des Titans' },
  { perso: 'Natsu Dragneel', univers: 'Fairy Tail' },

  { perso: 'Zelda', univers: 'The Legend of Zelda' },
  { perso: 'Boa Hancock', univers: 'One Piece' },
  { perso: 'Asuna Yuuki', univers: 'Sword Art Online' },
  { perso: 'Tifa Lockhart', univers: 'Final Fantasy VII' },
  { perso: '2B', univers: 'NieR Automata' },
  { perso: 'Hinata Hyuga', univers: 'Naruto' },
  { perso: 'Bulma', univers: 'Dragon Ball' },
  { perso: 'Ciri', univers: 'The Witcher' },
  { perso: 'Mikoto Misaka', univers: 'Toaru Majutsu no Index' },
  { perso: 'Violet Evergarden', univers: 'Violet Evergarden' },
  { perso: 'Mitsuri Kanroji', univers: 'Demon Slayer' },
  { perso: 'Ellie', univers: 'The Last of Us' },
  { perso: 'Midna', univers: 'The Legend of Zelda' },

  { perso: 'Sephiroth', univers: 'Final Fantasy VII' },
  { perso: 'Frieza', univers: 'Dragon Ball' },
  { perso: 'Esdeath', univers: 'Akame ga Kill!' },
  { perso: 'Madara Uchiha', univers: 'Naruto' },
  { perso: 'Ganondorf', univers: 'The Legend of Zelda' },
  { perso: 'Dio Brando', univers: 'JoJo’s Bizarre Adventure' },
  { perso: 'Griffith', univers: 'Berserk' },
  { perso: 'Handsome Jack', univers: 'Borderlands' },
  { perso: 'Mewtwo', univers: 'Pokémon' },
  { perso: 'Makima', univers: 'Chainsaw Man' },
  { perso: 'Arthas Menethil', univers: 'Warcraft' },
  { perso: 'Dracula', univers: 'Castlevania' },
  { perso: 'Albert Wesker', univers: 'Resident Evil' },

  { perso: 'Kirby', univers: 'Nintendo' },
  { perso: 'Deadpool', univers: 'Marvel' },
];
